# Generated by Django 5.0.2 on 2024-03-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acessorio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acessorio",
            old_name="acessorio",
            new_name="descricao",
        ),
    ]
