# Generated by Django 5.0.2 on 2024-07-01 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_modelo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modelos",
                to="core.categoria",
            ),
        ),
    ]
