# Generated by Django 5.0.2 on 2024-07-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_modelo_marca"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ano", models.CharField(default="0", max_length=10, null=True)),
                ("preco", models.CharField(default="0", max_length=100, null=True)),
                (
                    "acessorio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculos",
                        to="core.acessorio",
                    ),
                ),
                (
                    "cor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculos",
                        to="core.cor",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculos",
                        to="core.modelo",
                    ),
                ),
            ],
        ),
    ]
